### ISSUE TITLE
Repository (Temp Files)

### ISSUE THREAD

**Issue by amirisback** [fiqryq/Aplikasi-Pendeteksi-Gempa#1]
Coba Hapus .idea trus push ulang + tambahin code dibawah ini buat .gitignonre

*.iml
/.gradle
.gradle
.idea
/local.properties
/.idea/libraries
/.idea/modules.xml
/.idea/workspace.xml
.DS_Store
build
/build
/captures
.externalNativeBuild

built application files
.apk
.ap_

files for the dex VM
*.dex

Java class files
*.class

generated files
bin/
gen/
.externalNativeBuild/

Local configuration file (sdk path, etc)
local.properties
app/version.properties

**Comment by fiqryq** [comment]
donee
